steps:
  # --- Backend ---
  # 1. Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/draw-ai-backend', './backend']

  # 2. Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/draw-ai-backend']

  # 3. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'draw-ai-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/draw-ai-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1,AGENT_ID=${_AGENT_ID}'

  # --- Frontend ---
  # 4. Get Backend URL & Create .env
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching Cloud Run URL..."
        SERVICE_URL=$$(gcloud run services describe draw-ai-backend --platform managed --region us-central1 --format 'value(status.url)')
        echo "Detected Backend URL: $$SERVICE_URL"
        echo "VITE_BACKEND_URL=$$SERVICE_URL" > frontend/.env

  # 5. Install & Build Frontend
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm install
        npm run build

  # 6. Get Firebase Token
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud auth print-access-token > /workspace/firebase_token'

  # 7. Deploy to Firebase Hosting
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --project $PROJECT_ID --only hosting --token $(cat /workspace/firebase_token)

substitutions:
  _AGENT_ID: '294e322e-76ac-4644-8b7d-cd6c2d981359'

images:
  - 'gcr.io/$PROJECT_ID/draw-ai-backend'

options:
  logging: CLOUD_LOGGING_ONLY
