steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/draw-ai-backend', './backend']

  # 2. Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/draw-ai-backend']

  # 3. Deploy container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'draw-ai-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/draw-ai-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1,AGENT_ID=${_AGENT_ID}'

substitutions:
  _AGENT_ID: '294e322e-76ac-4644-8b7d-cd6c2d981359'

images:
  - 'gcr.io/$PROJECT_ID/draw-ai-backend'
